name: GitHub to Lark Notification

on:
  pull_request:
    types: [opened, reopened, closed, synchronize, ready_for_review, converted_to_draft]
  push:
    branches:
      - main
      - develop
      - "feature/*"
      - "fix/*"
  issues:
    types: [opened, closed, reopened, edited]
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]
  workflow_run:
    workflows: ["Rust", "External crates", "Documentation", "Docs CI", "Native Bridge", "IDE Tests", "Move Formatter", "Code Coverage", "Turborepo CI", "Validate Release Notes"]
    types: [completed]
  release:
    types: [published, created]
  discussion:
    types: [created]

env:
  LARK_WEBHOOK: ${{ secrets.LARK_WEBHOOK }}
  LARK_SECRET: ${{ secrets.LARK_SECRET }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Notify to Lark
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_ACTION: ${{ github.event.action }}
          GITHUB_EVENT_STATUS: ${{ github.event.workflow_run.conclusion }}
          GITHUB_EVENT_REPO: ${{ github.repository }}
          GITHUB_EVENT_REPO_NAME: ${{ github.event.repository.name }}
          GITHUB_EVENT_REPO_OWNER: ${{ github.repository_owner }}
          GITHUB_EVENT_ACTOR: ${{ github.actor }}
          GITHUB_EVENT_PR_TITLE: ${{ github.event.pull_request.title }}
          GITHUB_EVENT_PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_EVENT_PR_USER: ${{ github.event.pull_request.user.login }}
          GITHUB_EVENT_PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_EVENT_PR_BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
          GITHUB_EVENT_PR_HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}
          GITHUB_EVENT_PR_DRAFT: ${{ github.event.pull_request.draft }}
          GITHUB_EVENT_PR_MERGED: ${{ github.event.pull_request.merged }}
          GITHUB_EVENT_PR_ADDITIONS: ${{ github.event.pull_request.additions }}
          GITHUB_EVENT_PR_DELETIONS: ${{ github.event.pull_request.deletions }}
          GITHUB_EVENT_PR_CHANGED_FILES: ${{ github.event.pull_request.changed_files }}
          GITHUB_EVENT_COMMIT_SHA: ${{ github.sha }}
          GITHUB_EVENT_REF_NAME: ${{ github.ref_name }}
          GITHUB_EVENT_HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          GITHUB_EVENT_HEAD_COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
          GITHUB_EVENT_WORKFLOW_NAME: ${{ github.event.workflow_run.name }}
          GITHUB_EVENT_WORKFLOW_URL: ${{ github.event.workflow_run.html_url }}
          GITHUB_EVENT_WORKFLOW_BRANCH: ${{ github.event.workflow_run.head_branch }}
          GITHUB_EVENT_WORKFLOW_ACTOR: ${{ github.event.workflow_run.actor.login }}
          GITHUB_EVENT_WORKFLOW_RUN_ID: ${{ github.event.workflow_run.id }}
          GITHUB_EVENT_WORKFLOW_COMMIT_SHA: ${{ github.event.workflow_run.head_sha }}
        run: |
          chmod +x .github/scripts/lark_notify.sh
          ./.github/scripts/lark_notify.sh
